apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cart-page-rs
  namespace: shravya-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      web: cart
  template: #It define which application that we have to apply in a cluster(pod defintion)
    metadata:
      labels:
        web: cart
    spec: #It defines behavioour of the pod and its containers
      containers:
        - name: cart-container
          image: muralisocial123/cart-page-test:1.0
          ports:
            - containerPort: 3000